package staffmanagementsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author User
 */
public class DeleteUser extends javax.swing.JFrame {

    String userName;
    String jobTitle;
    String back;
    int count;
    int selectId;
    String selectPos;
    String selectStatus;

    /**
     * Creates new form DeleteUser
     */
    public DeleteUser() {
        initComponents();
    }

    public DeleteUser(String username, String jobtitle, String Back) {
        initComponents();
        userName = username;
        jobTitle = jobtitle;
        back = Back;
        Admin.setEnabled(false);
        Staff.setEnabled(false);
        Single.setEnabled(false);
        Married.setEnabled(false);
        showUsers();
         usersdetails.setAutoCreateRowSorter(true);
    }

    //put the user list in the datbase to the usersList
    public ArrayList<Admin> usersList() {
        ArrayList<Admin> usersList = new ArrayList<>();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://110.4.45.41:3306/myvoicem_sms", "myvoicem_admin", "Pintechpintech1");
            String sql = "Select * from login ";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            Admin users;
            while (rs.next()) {
                users = new Admin(rs.getInt("ID"), rs.getInt("salary"), rs.getString("name"), rs.getString("maritial_status"), rs.getString("username"), rs.getString("job_title"), rs.getString("password"));
                usersList.add(users);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return usersList;
    }

    ;  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        position = new javax.swing.ButtonGroup();
        status = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        home = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Single = new javax.swing.JRadioButton();
        delete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        Staff = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Admin = new javax.swing.JRadioButton();
        fullname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Married = new javax.swing.JRadioButton();
        username = new javax.swing.JTextField();
        salary = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        clearBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        refresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersdetails = new javax.swing.JTable();
        deleteFullname = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/deleteStaff.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Delete User");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 140, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 130));

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/home.png"))); // NOI18N
        home.setText("Main Menu");
        home.setBorder(null);
        home.setBorderPainted(false);
        home.setContentAreaFilled(false);
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel2.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, -1, -1));

        logoutBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/logout.png"))); // NOI18N
        logoutBtn.setText("Log Out");
        logoutBtn.setBorder(null);
        logoutBtn.setBorderPainted(false);
        logoutBtn.setContentAreaFilled(false);
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutBtnMouseExited(evt);
            }
        });
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        jPanel2.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, -1, -1));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/Back.png"))); // NOI18N
        backBtn.setBorder(null);
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel2.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 720, 1120, 60));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Single.setBackground(new java.awt.Color(255, 255, 255));
        status.add(Single);
        Single.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Single.setText("Single");
        jPanel3.add(Single, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, -1, -1));

        delete.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel3.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, -1, -1));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 19)); // NOI18N
        jLabel6.setText("Password :");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        password.setEditable(false);
        password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        password.setBorder(null);
        password.setOpaque(false);
        jPanel3.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 187, 35));

        Staff.setBackground(new java.awt.Color(255, 255, 255));
        position.add(Staff);
        Staff.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Staff.setText("Staff");
        jPanel3.add(Staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 85, -1));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 19)); // NOI18N
        jLabel5.setText("Position :");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 19)); // NOI18N
        jLabel2.setText("User Name :");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        ID.setEditable(false);
        ID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ID.setBorder(null);
        ID.setOpaque(false);
        jPanel3.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 182, 36));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 19)); // NOI18N
        jLabel1.setText("ID :");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        Admin.setBackground(new java.awt.Color(255, 255, 255));
        position.add(Admin);
        Admin.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Admin.setText("Admin");
        jPanel3.add(Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        fullname.setEditable(false);
        fullname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fullname.setBorder(null);
        fullname.setOpaque(false);
        jPanel3.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 182, 35));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 19)); // NOI18N
        jLabel4.setText("Salary :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        Married.setBackground(new java.awt.Color(255, 255, 255));
        status.add(Married);
        Married.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Married.setText("Married");
        Married.setToolTipText("");
        jPanel3.add(Married, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, -1, -1));

        username.setEditable(false);
        username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        username.setBorder(null);
        username.setOpaque(false);
        jPanel3.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 182, 39));

        salary.setEditable(false);
        salary.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        salary.setBorder(null);
        salary.setOpaque(false);
        jPanel3.add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 182, 36));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 19)); // NOI18N
        jLabel3.setText("Full Name :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 19)); // NOI18N
        jLabel7.setText("Maritial Status :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        clearBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        jPanel3.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 400, 590));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        refresh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/refresh.png"))); // NOI18N
        refresh.setBorder(null);
        refresh.setBorderPainted(false);
        refresh.setContentAreaFilled(false);
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                refreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refreshMouseExited(evt);
            }
        });
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel4.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 40, 40));

        usersdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Maritial_Status", "Salary", "Job_Title", "Username", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        usersdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersdetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(usersdetails);
        if (usersdetails.getColumnModel().getColumnCount() > 0) {
            usersdetails.getColumnModel().getColumn(6).setHeaderValue("Password");
        }

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 670, 482));

        deleteFullname.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        deleteFullname.setText("Delete by entering username");
        deleteFullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFullnameActionPerformed(evt);
            }
        });
        jPanel4.add(deleteFullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 540, 250, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 720, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        Homepage home = new Homepage(userName, jobTitle);
        FadeUtilityClass fades = new FadeUtilityClass();
        fades.fade(home, true);
        home.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_homeActionPerformed

    //fill the text box with the details which admin click
    private void usersdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersdetailsMouseClicked
        int a = usersdetails.getSelectedRow();
        TableModel model = usersdetails.getModel();
        selectId = (int) model.getValueAt(a, 0);
        selectPos = model.getValueAt(a, 4).toString();
        selectStatus = model.getValueAt(a, 2).toString();

        if ("admin".equals(selectPos)) {
            Admin.setSelected(true);

        }
        if ("staff".equals(selectPos)) {
            Staff.setSelected(true);
        }

        if ("single".equals(selectStatus)) {
            Single.setSelected(true);
        }
        if ("married".equals(selectStatus)) {
            Married.setSelected(true);
        }

        ID.setText(model.getValueAt(a, 0).toString());
        username.setText(model.getValueAt(a, 5).toString());
        fullname.setText(model.getValueAt(a, 1).toString());
        salary.setText(model.getValueAt(a, 3).toString());
        password.setText(model.getValueAt(a, 6).toString());

    }//GEN-LAST:event_usersdetailsMouseClicked

    //delete the details that put in the textbox, if the job title is admin, admin will not be able to delete it
    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        if ("admin".equals(selectPos)) {
            JOptionPane.showMessageDialog(null, "You cannot delete Admin");
        } else if (username.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please select a user to delete");
        } else {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you really want to delete this user?", "Warning", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {
                Admin admin = new Admin();
                admin.delete(selectId);
                position.clearSelection();
                status.clearSelection();
                ID.setText("");
                fullname.setText("");
                salary.setText("");
                username.setText("");
                password.setText("");
                DefaultTableModel model = (DefaultTableModel) usersdetails.getModel();
                model.setRowCount(0);
                showUsers();
            } else {
                JOptionPane.showMessageDialog(null, "User deletion is cancelled.");
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        DefaultTableModel model = (DefaultTableModel) usersdetails.getModel();
        model.setRowCount(0);
        showUsers();
    }//GEN-LAST:event_refreshActionPerformed

    private void deleteFullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFullnameActionPerformed
        DeleteUserByUserName delete = new DeleteUserByUserName(userName, jobTitle, back);
        FadeUtilityClass fades = new FadeUtilityClass();
        fades.fade(delete, true);
        delete.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_deleteFullnameActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Do you really want to log out?", "Warning", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "User Log Out");
            User user = new User();
            FadeUtilityClass fades = new FadeUtilityClass();
            fades.fade(user, true);
            user.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void refreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseEntered
        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/refresh1.png")));
    }//GEN-LAST:event_refreshMouseEntered

    private void refreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseExited
        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/refresh.png")));
    }//GEN-LAST:event_refreshMouseExited

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/home1.png")));
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/home.png")));
    }//GEN-LAST:event_homeMouseExited

    private void logoutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseEntered
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/logout_1.png")));
    }//GEN-LAST:event_logoutBtnMouseEntered

    private void logoutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseExited
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/logout.png")));
    }//GEN-LAST:event_logoutBtnMouseExited

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        if (back.equals("details")) {
            StaffDetails staff = new StaffDetails(userName, jobTitle);
            FadeUtilityClass fades = new FadeUtilityClass();
            fades.fade(staff, true);
            staff.setVisible(true);
            setVisible(false);
        } else {
            ManageStaff manage = new ManageStaff(userName, jobTitle);
            FadeUtilityClass fades = new FadeUtilityClass();
            fades.fade(manage, true);
            manage.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_backBtnActionPerformed

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/back1.png")));
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/back.png")));
    }//GEN-LAST:event_backBtnMouseExited

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed

        position.clearSelection();
        status.clearSelection();
        ID.setText("");
        fullname.setText("");
        salary.setText("");
        username.setText("");
        password.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteUser().setVisible(true);
            }
        });
    }

    //show the user in the list in the table
    private void showUsers() {
        ArrayList<Admin> list = usersList();
        DefaultTableModel model = (DefaultTableModel) usersdetails.getModel();
        Object[] row = new Object[7];
        for (int i = 0; i < list.size(); i++) {

            row[0] = list.get(i).getId();
            row[1] = list.get(i).getName();
            row[2] = list.get(i).getMaritial_status();
            row[3] = list.get(i).getSalary();
            row[4] = list.get(i).getJob_title();
            row[5] = list.get(i).getUsername();
            if(list.get(i).getJob_title().equals("admin"))
            {
            row[6] = "****";
            }
            else
            {
            row[6] = list.get(i).getPassword(); 
            }
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Admin;
    private javax.swing.JTextField ID;
    private javax.swing.JRadioButton Married;
    private javax.swing.JRadioButton Single;
    private javax.swing.JRadioButton Staff;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton delete;
    private javax.swing.JButton deleteFullname;
    private javax.swing.JTextField fullname;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPasswordField password;
    private javax.swing.ButtonGroup position;
    private javax.swing.JButton refresh;
    private javax.swing.JTextField salary;
    private javax.swing.ButtonGroup status;
    private javax.swing.JTextField username;
    private javax.swing.JTable usersdetails;
    // End of variables declaration//GEN-END:variables
}
