/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package staffmanagementsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class PersonalProfile extends javax.swing.JFrame {

    String userName;
    String jobTitle;
    int count;

    /**
     * Creates new form PersonalProfile
     */
    public PersonalProfile() {
        initComponents();
    }

    public PersonalProfile(String username, String jobtitle) {
        initComponents();
        userName = username;
        jobTitle = jobtitle;
        showData(userName, jobTitle);
        Save.setVisible(false);
        changeName.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MStatus = new javax.swing.ButtonGroup();
        pos = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        changeName = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Admin = new javax.swing.JRadioButton();
        Password = new javax.swing.JTextField();
        Married = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        Staff = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        FullName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        Salary = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        Single = new javax.swing.JRadioButton();
        JLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 23)); // NOI18N
        jLabel2.setText("User Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        changeName.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        changeName.setText("Change User Name");
        changeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeNameActionPerformed(evt);
            }
        });
        jPanel1.add(changeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, -1, -1));

        Edit.setFont(new java.awt.Font("Berlin Sans FB", 0, 23)); // NOI18N
        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        jPanel1.add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 590, -1, -1));

        Admin.setBackground(new java.awt.Color(255, 255, 255));
        pos.add(Admin);
        Admin.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        Admin.setText("Admin");
        Admin.setEnabled(false);
        jPanel1.add(Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));

        Password.setEditable(false);
        Password.setBackground(new java.awt.Color(255, 255, 255));
        Password.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        Password.setText("Password");
        Password.setBorder(null);
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 219, 30));

        Married.setBackground(new java.awt.Color(255, 255, 255));
        MStatus.add(Married);
        Married.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        Married.setText("Married");
        Married.setEnabled(false);
        jPanel1.add(Married, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, -1, -1));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 23)); // NOI18N
        jLabel6.setText("Maritial Status:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, -1, -1));

        Staff.setBackground(new java.awt.Color(255, 255, 255));
        pos.add(Staff);
        Staff.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        Staff.setText("Staff");
        Staff.setEnabled(false);
        Staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffActionPerformed(evt);
            }
        });
        jPanel1.add(Staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, -1, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 23)); // NOI18N
        jLabel3.setText("Full Name :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 23)); // NOI18N
        jLabel5.setText("Job Title :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, -1, -1));

        FullName.setEditable(false);
        FullName.setBackground(new java.awt.Color(255, 255, 255));
        FullName.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        FullName.setText("Full Name");
        FullName.setBorder(null);
        FullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullNameActionPerformed(evt);
            }
        });
        jPanel1.add(FullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 217, 30));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 23)); // NOI18N
        jLabel4.setText("Salary :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        Save.setFont(new java.awt.Font("Berlin Sans FB", 0, 23)); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPanel1.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 590, -1, -1));

        Salary.setEditable(false);
        Salary.setBackground(new java.awt.Color(255, 255, 255));
        Salary.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        Salary.setText("Salary");
        Salary.setBorder(null);
        jPanel1.add(Salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 220, 30));

        name.setEditable(false);
        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        name.setText("Name");
        name.setBorder(null);
        name.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 36, 217, 33));

        Single.setBackground(new java.awt.Color(255, 255, 255));
        MStatus.add(Single);
        Single.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        Single.setText("Single");
        Single.setEnabled(false);
        jPanel1.add(Single, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, -1, -1));

        JLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 23)); // NOI18N
        JLabel1.setText("Password :");
        jPanel1.add(JLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 130, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 219, 33));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 69, 217, 17));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 217, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 221, 10));

        jPanel3.setBackground(new java.awt.Color(51, 0, 51));

        logoutBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/logout.png"))); // NOI18N
        logoutBtn.setText("Log Out");
        logoutBtn.setBorder(null);
        logoutBtn.setBorderPainted(false);
        logoutBtn.setContentAreaFilled(false);
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutBtnMouseExited(evt);
            }
        });
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        homeBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/Back.png"))); // NOI18N
        homeBtn.setBorder(null);
        homeBtn.setBorderPainted(false);
        homeBtn.setContentAreaFilled(false);
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeBtnMouseExited(evt);
            }
        });
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 563, Short.MAX_VALUE)
                .addComponent(logoutBtn)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(logoutBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 720, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 720, -1));

        jPanel2.setBackground(new java.awt.Color(51, 0, 61));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("My Profile");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(jLabel1)
                .addContainerGap(231, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 130));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //navigate user to the main menu of the system
    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        Homepage home = new Homepage(userName, jobTitle);
        home.setVisible(true);
        FadeUtilityClass fades = new FadeUtilityClass();
        fades.fade(home, true);
        setVisible(false);
    }//GEN-LAST:event_homeBtnActionPerformed

    //set the text box become editable
    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        Password.setEditable(true);

        FullName.setEditable(true);
        Salary.setEditable(true);
        Single.setEnabled(true);
        Married.setEnabled(true);
        Staff.setEnabled(true);
        Admin.setEnabled(true);
        Save.setVisible(true);
        changeName.setVisible(true);

    }//GEN-LAST:event_EditActionPerformed

    
    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        updateDetails(userName);

    }//GEN-LAST:event_SaveActionPerformed

    private void changeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeNameActionPerformed
        changeName(userName);
    }//GEN-LAST:event_changeNameActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void FullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FullNameActionPerformed

    private void homeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseEntered
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/back1.png")));
    }//GEN-LAST:event_homeBtnMouseEntered

    private void homeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseExited
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/Back.png")));
    }//GEN-LAST:event_homeBtnMouseExited

    private void StaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StaffActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Do you really want to log out?", "Warning", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "User Log Out");
            User user = new User();
            FadeUtilityClass fades = new FadeUtilityClass();
            fades.fade(user, true);
            user.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void logoutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseEntered
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/logout_1.png")));
    }//GEN-LAST:event_logoutBtnMouseEntered

    private void logoutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseExited
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/logout.png")));
    }//GEN-LAST:event_logoutBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonalProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonalProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonalProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonalProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonalProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Admin;
    private javax.swing.JButton Edit;
    private javax.swing.JTextField FullName;
    private javax.swing.JLabel JLabel1;
    private javax.swing.ButtonGroup MStatus;
    private javax.swing.JRadioButton Married;
    private javax.swing.JTextField Password;
    private javax.swing.JTextField Salary;
    private javax.swing.JButton Save;
    private javax.swing.JRadioButton Single;
    private javax.swing.JRadioButton Staff;
    private javax.swing.JButton changeName;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTextField name;
    private javax.swing.ButtonGroup pos;
    // End of variables declaration//GEN-END:variables

    private void showData(String userName, String jobTitle) {

        String Mstatus;
        String JTitle;
        Admin admin = new Admin();
        ArrayList<details> Profile = admin.viewProfile(userName);
        Password.setText(Profile.get(0).getPassword());
        name.setText(Profile.get(0).getUsername());
        FullName.setText(Profile.get(0).getName());
        JTitle = Profile.get(0).getJob_title();
        if ("admin".equals(JTitle)) {
            Admin.setSelected(true);
        } else {
            Staff.setSelected(true);
        }
        Salary.setText(Integer.toString(Profile.get(0).getSalary()));
        Mstatus = Profile.get(0).getMaritial_status();
        if ("single".equals(Mstatus)) {
            Single.setSelected(true);
        } else {
            Married.setSelected(true);
        }

//        try {
//            String Mstatus;
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/sms", "root", "");
//            String sql = "Select * from login where username=?";
//            PreparedStatement pst = con.prepareStatement(sql);
//            pst.setString(1, userName);
//            ResultSet rs = pst.executeQuery();
//
//            if (rs.next()) {
//                Password.setText(rs.getString("password"));
//                name.setText(rs.getString("username"));
//                FullName.setText(rs.getString("name"));
//                JobTitle.setText(rs.getString("job_title"));
//                Salary.setText(rs.getString("salary"));
//                Mstatus = rs.getString("maritial_status");
//                if ("single".equals(Mstatus)) {
//                    Single.setSelected(true);
//                } else {
//                    Married.setSelected(true);
//                }
//
//            } else {
//                JOptionPane.showMessageDialog(null, "ERROR");
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(ManageStaff.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    private void changeName(String userName) {
        Password.setEditable(false);
        FullName.setEditable(false);
        Salary.setEditable(false);
        Single.setEnabled(false);
        Married.setEnabled(false);
        name.setEditable(true);

        if (JOptionPane.showConfirmDialog(null, "You must edit the username. Are you sure?", "WARNING",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            ChangeUserName change = new ChangeUserName(userName, jobTitle);
            FadeUtilityClass fades = new FadeUtilityClass();
            fades.fade(change, true);
            change.setVisible(true);
            setVisible(false);
        } else {

            setVisible(true);
        }

    }

    private void updateDetails(String userName) {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://110.4.45.41:3306/myvoicem_sms", "myvoicem_admin", "Pintechpintech1");
            String sql3 = "Select * from login where username=?";
            PreparedStatement pst3 = con.prepareStatement(sql3);
            pst3.setString(1, name.getText());
            ResultSet rs3 = pst3.executeQuery();
            while (rs3.next()) {
                count++;
            }

            String sql = "UPDATE login SET name=?, maritial_status=?,salary=?,job_title=?,password=? where username=? and ID!=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, FullName.getText());
            String Mstatus = "";
            if (Single.isSelected()) {
                Mstatus = "single";
            }
            if (Married.isSelected()) {
                Mstatus = "married";
            }
            if (Staff.isSelected()) {
                jobTitle = "staff";
            }
            if (Admin.isSelected()) {
                jobTitle = "admin";
            }
            pst.setString(2, Mstatus);
            pst.setString(3, Salary.getText());
            pst.setString(4, jobTitle);
            pst.setString(5, Password.getText());
            pst.setString(6, userName);
            pst.setInt(7, count);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Update Successful.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }
}
