package staffmanagementsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import staffmanagementsystem.Admin;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author User
 */
public class SearchUserByFullName extends javax.swing.JFrame {

    String userName;
    String jobTitle;
    String back;

    public SearchUserByFullName() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public SearchUserByFullName(String Username, String JobTitle, String Back) {
        initComponents();
        this.setLocationRelativeTo(null);
        userName = Username;
        jobTitle = JobTitle;
        back = Back;
        showUsers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pos = new javax.swing.ButtonGroup();
        status = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersdetails = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        searchBtn = new javax.swing.JButton();
        fullname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        salary = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        fullname5 = new javax.swing.JTextField();
        Admin = new javax.swing.JRadioButton();
        Staff = new javax.swing.JRadioButton();
        Single = new javax.swing.JRadioButton();
        Married = new javax.swing.JRadioButton();
        clearBtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usersdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Maritial_Status", "Salary", "Job_Title", "Username", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        usersdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersdetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(usersdetails);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 670, 500));

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/searchStaff.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search User");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 130));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        jPanel2.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, -1, -1));

        fullname.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        fullname.setBorder(null);
        jPanel2.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 190, 30));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 19)); // NOI18N
        jLabel3.setText("ID :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 30, -1));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 19)); // NOI18N
        jLabel4.setText("Username :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 19)); // NOI18N
        jLabel5.setText("Full Name :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 19)); // NOI18N
        jLabel6.setText("Salary :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 19)); // NOI18N
        jLabel7.setText("Position :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 19)); // NOI18N
        jLabel8.setText("Password :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 19)); // NOI18N
        jLabel9.setText("Maritial Status :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        username.setEditable(false);
        username.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        username.setBorder(null);
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 190, 30));

        salary.setEditable(false);
        salary.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        salary.setBorder(null);
        jPanel2.add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 190, 30));

        password.setEditable(false);
        password.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        password.setBorder(null);
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 190, 30));

        id.setEditable(false);
        id.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        id.setBorder(null);
        jPanel2.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 190, 30));
        jPanel2.add(fullname5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 190, 30));

        Admin.setBackground(new java.awt.Color(255, 255, 255));
        pos.add(Admin);
        Admin.setFont(new java.awt.Font("Berlin Sans FB", 0, 17)); // NOI18N
        Admin.setText("Admin");
        jPanel2.add(Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 80, -1));

        Staff.setBackground(new java.awt.Color(255, 255, 255));
        pos.add(Staff);
        Staff.setFont(new java.awt.Font("Berlin Sans FB", 0, 17)); // NOI18N
        Staff.setText("Staff");
        jPanel2.add(Staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, -1));

        Single.setBackground(new java.awt.Color(255, 255, 255));
        status.add(Single);
        Single.setFont(new java.awt.Font("Berlin Sans FB", 0, 17)); // NOI18N
        Single.setText("Single");
        jPanel2.add(Single, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 80, -1));

        Married.setBackground(new java.awt.Color(255, 255, 255));
        status.add(Married);
        Married.setFont(new java.awt.Font("Berlin Sans FB", 0, 17)); // NOI18N
        Married.setText("Married");
        jPanel2.add(Married, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, -1, -1));

        clearBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 17)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        jPanel2.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, -1, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 190, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 390, 570));

        jPanel3.setBackground(new java.awt.Color(51, 0, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/Back.png"))); // NOI18N
        backBtn.setBorder(null);
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel3.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        logoutBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/logout.png"))); // NOI18N
        logoutBtn.setText("Log Out");
        logoutBtn.setBorder(null);
        logoutBtn.setBorderPainted(false);
        logoutBtn.setContentAreaFilled(false);
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutBtnMouseExited(evt);
            }
        });
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        jPanel3.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, -1, -1));

        homeBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/home.png"))); // NOI18N
        homeBtn.setText("Main Menu");
        homeBtn.setBorder(null);
        homeBtn.setBorderPainted(false);
        homeBtn.setContentAreaFilled(false);
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeBtnMouseExited(evt);
            }
        });
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jPanel3.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, -1, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 1100, 60));

        refreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/refresh.png"))); // NOI18N
        refreshBtn.setBorder(null);
        refreshBtn.setBorderPainted(false);
        refreshBtn.setContentAreaFilled(false);
        refreshBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                refreshBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refreshBtnMouseExited(evt);
            }
        });
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        getContentPane().add(refreshBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 140, 40, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        if (fullname.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter full name to search");
        } else {
            showSearch(fullname.getText());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void usersdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersdetailsMouseClicked
        int a = usersdetails.getSelectedRow();
        TableModel model = usersdetails.getModel();
        int selectId = (int) model.getValueAt(a, 0);
        String selectPos = model.getValueAt(a, 4).toString();
        String selectStatus = model.getValueAt(a, 2).toString();

        if ("admin".equals(selectPos)) {
            Admin.setSelected(true);

        }
        if ("staff".equals(selectPos)) {
            Staff.setSelected(true);
        }

        if ("single".equals(selectStatus)) {
            Single.setSelected(true);
        }
        if ("married".equals(selectStatus)) {
            Married.setSelected(true);
        }

        id.setText(model.getValueAt(a, 0).toString());
        username.setText(model.getValueAt(a, 5).toString());
        fullname.setText(model.getValueAt(a, 1).toString());
        salary.setText(model.getValueAt(a, 3).toString());
        password.setText(model.getValueAt(a, 6).toString());
    }//GEN-LAST:event_usersdetailsMouseClicked

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) usersdetails.getModel();
        model.setRowCount(0);
        showUsers();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        pos.clearSelection();
        status.clearSelection();
        id.setText("");
        fullname.setText("");
        salary.setText("");
        username.setText("");
        password.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        SearchUser search = new SearchUser(userName, jobTitle, back);
        FadeUtilityClass fades = new FadeUtilityClass();
        fades.fade(search, true);
        search.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        Homepage home = new Homepage(userName, jobTitle);
        FadeUtilityClass fades = new FadeUtilityClass();
        fades.fade(home, true);
        home.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Do you really want to log out?", "Warning", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "User Log Out");
            User user = new User();
            FadeUtilityClass fades = new FadeUtilityClass();
            fades.fade(user, true);
            user.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/back1.png")));
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/Back.png")));
    }//GEN-LAST:event_backBtnMouseExited

    private void homeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseEntered
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/home1.png")));
    }//GEN-LAST:event_homeBtnMouseEntered

    private void homeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseExited
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/home.png")));
    }//GEN-LAST:event_homeBtnMouseExited

    private void logoutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseEntered
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/logout_1.png")));
    }//GEN-LAST:event_logoutBtnMouseEntered

    private void logoutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseExited
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/logout.png")));
    }//GEN-LAST:event_logoutBtnMouseExited

    private void refreshBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshBtnMouseEntered
        refreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/refresh1.png")));
    }//GEN-LAST:event_refreshBtnMouseEntered

    private void refreshBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshBtnMouseExited
        refreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/refresh.png")));
    }//GEN-LAST:event_refreshBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchUserByFullName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchUserByFullName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchUserByFullName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchUserByFullName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchUserByFullName().setVisible(true);
            }
        });
    }

    public ArrayList<Admin> usersList() {
        ArrayList<Admin> usersList = new ArrayList<>();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/sms", "root", "");
            String sql = "Select * from login ";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            Admin users;

            while (rs.next()) {
                users = new Admin(rs.getInt("ID"), rs.getInt("salary"), rs.getString("name"), rs.getString("maritial_status"), rs.getString("username"), rs.getString("job_title"), rs.getString("password"));
                usersList.add(users);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return usersList;
    }

    private void showUsers() {
        ArrayList<Admin> list = usersList();
        DefaultTableModel model = (DefaultTableModel) usersdetails.getModel();
        Object[] row = new Object[7];
        for (int i = 0; i < list.size(); i++) {

            row[0] = list.get(i).getId();
            row[1] = list.get(i).getName();
            row[2] = list.get(i).getMaritial_status();
            row[3] = list.get(i).getSalary();
            row[4] = list.get(i).getJob_title();
            row[5] = list.get(i).getUsername();
            if (list.get(i).getJob_title().equals("admin")) {
                row[6] = "****";
            } else {
                row[6] = list.get(i).getPassword();
            }
            model.addRow(row);
        }
    }

    public ArrayList<Admin> searchList(String FULLNAME) {
        ArrayList<Admin> searchlist = new ArrayList<>();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://110.4.45.41:3306/myvoicem_sms", "myvoicem_admin", "Pintechpintech1");
            String sql1 = "Select * from login where name=?";
            PreparedStatement pst3 = con.prepareStatement(sql1);
            pst3.setString(1, FULLNAME);
            ResultSet rs3 = pst3.executeQuery();
            if (rs3.next()) {
                DefaultTableModel model = (DefaultTableModel) usersdetails.getModel();
                model.setRowCount(0);
                String sql = "Select * from login where name=?";
                PreparedStatement pst2 = con.prepareStatement(sql);
                pst2.setString(1, FULLNAME);
                ResultSet rs2 = pst2.executeQuery();
                Admin users;

                while (rs2.next()) {
                    users = new Admin(rs2.getInt("ID"), rs2.getInt("salary"), rs2.getString("name"), rs2.getString("maritial_status"), rs2.getString("username"), rs2.getString("job_title"), rs2.getString("password"));
                    searchlist.add(users);
                }
            } else {
                JOptionPane.showMessageDialog(null, "User do not exists");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return searchlist;
    }

    private void showSearch(String fullName) {
        ArrayList<Admin> slist = searchList(fullName);
        DefaultTableModel model = (DefaultTableModel) usersdetails.getModel();
        Object[] row = new Object[7];
        for (int i = 0; i < slist.size(); i++) {

            row[0] = slist.get(i).getId();
            row[1] = slist.get(i).getName();
            row[2] = slist.get(i).getMaritial_status();
            row[3] = slist.get(i).getSalary();
            row[4] = slist.get(i).getJob_title();
            row[5] = slist.get(i).getUsername();
            if (slist.get(i).getJob_title().equals("admin")) {
                row[6] = "****";
            } else {
                row[6] = slist.get(i).getPassword();
            }
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Admin;
    private javax.swing.JRadioButton Married;
    private javax.swing.JRadioButton Single;
    private javax.swing.JRadioButton Staff;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JTextField fullname;
    private javax.swing.JTextField fullname5;
    private javax.swing.JButton homeBtn;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTextField password;
    private javax.swing.ButtonGroup pos;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTextField salary;
    private javax.swing.JButton searchBtn;
    private javax.swing.ButtonGroup status;
    private javax.swing.JTextField username;
    private javax.swing.JTable usersdetails;
    // End of variables declaration//GEN-END:variables
}
