/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package staffmanagementsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author User
 */
public class UpdateUser extends javax.swing.JFrame {

    String userName;
    String jobTitle;
    String back;
    int selectId;
    String selectPos;
    String selectStatus;

    /**
     * Creates new form UpdateUser
     */
    public UpdateUser() {
        initComponents();
    }

    public UpdateUser(String username, String jobtitle, String Back) {
        initComponents();
        userName = username;
        jobTitle = jobtitle;
        back = Back;
        showUsers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pos = new javax.swing.ButtonGroup();
        status = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        fullname = new javax.swing.JTextField();
        salary = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        Admin = new javax.swing.JRadioButton();
        Staff = new javax.swing.JRadioButton();
        Single = new javax.swing.JRadioButton();
        Married = new javax.swing.JRadioButton();
        updateBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        clearBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersdetails = new javax.swing.JTable();
        refreshBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(51, 0, 51));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/editStaff.png"))); // NOI18N
        jLabel8.setToolTipText("");
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 17, -1, -1));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Edit User");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 76, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 130));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 19)); // NOI18N
        jLabel1.setText("ID :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 30, 40));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 19)); // NOI18N
        jLabel2.setText("Username :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 100, 30));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 19)); // NOI18N
        jLabel3.setText("Full Name :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, 30));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 19)); // NOI18N
        jLabel4.setText("Salary :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 70, 30));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 19)); // NOI18N
        jLabel5.setText("Position :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 80, 30));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 19)); // NOI18N
        jLabel6.setText("Password :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 100, 30));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 19)); // NOI18N
        jLabel7.setText("Maritial Status :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, 30));

        ID.setEditable(false);
        ID.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        ID.setBorder(null);
        ID.setOpaque(false);
        jPanel2.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 185, 30));

        username.setEditable(false);
        username.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        username.setBorder(null);
        username.setOpaque(false);
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 185, 35));

        fullname.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        fullname.setBorder(null);
        fullname.setOpaque(false);
        jPanel2.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 185, 30));

        salary.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        salary.setBorder(null);
        salary.setOpaque(false);
        jPanel2.add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 185, 30));

        password.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        password.setBorder(null);
        password.setOpaque(false);
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 160, 30));

        Admin.setBackground(new java.awt.Color(255, 255, 255));
        pos.add(Admin);
        Admin.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Admin.setText("Admin");
        jPanel2.add(Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        pos.add(Staff);
        Staff.setFont(new java.awt.Font("Berlin Sans FB", 0, 21)); // NOI18N
        Staff.setText("Staff");
        Staff.setContentAreaFilled(false);
        jPanel2.add(Staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, -1));

        status.add(Single);
        Single.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Single.setText("Single");
        Single.setContentAreaFilled(false);
        jPanel2.add(Single, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, -1, -1));

        status.add(Married);
        Married.setFont(new java.awt.Font("Berlin Sans FB", 0, 19)); // NOI18N
        Married.setText("Married");
        Married.setContentAreaFilled(false);
        jPanel2.add(Married, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, -1, -1));

        updateBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel2.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 180, 10));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 190, 10));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 160, 10));

        clearBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        jPanel2.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, -1, -1));

        viewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/unview.png"))); // NOI18N
        viewBtn.setBorder(null);
        viewBtn.setBorderPainted(false);
        viewBtn.setContentAreaFilled(false);
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        jPanel2.add(viewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 401, 40, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 390, 580));

        jPanel5.setBackground(new java.awt.Color(0, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usersdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Maritial_Status", "Salary", "Job_Title", "Username", "Password"
            }
        ));
        usersdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersdetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(usersdetails);
        if (usersdetails.getColumnModel().getColumnCount() > 0) {
            usersdetails.getColumnModel().getColumn(6).setHeaderValue("Password");
        }

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 697, 490));

        refreshBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        refreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/refresh.png"))); // NOI18N
        refreshBtn.setBorder(null);
        refreshBtn.setBorderPainted(false);
        refreshBtn.setContentAreaFilled(false);
        refreshBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                refreshBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refreshBtnMouseExited(evt);
            }
        });
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        jPanel5.add(refreshBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 30, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 730, 580));

        jPanel4.setBackground(new java.awt.Color(51, 0, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/logout.png"))); // NOI18N
        logoutBtn.setText("Log Out");
        logoutBtn.setBorder(null);
        logoutBtn.setBorderPainted(false);
        logoutBtn.setContentAreaFilled(false);
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutBtnMouseExited(evt);
            }
        });
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        jPanel4.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 6, -1, -1));

        homeBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/home.png"))); // NOI18N
        homeBtn.setText("Main Menu");
        homeBtn.setBorder(null);
        homeBtn.setBorderPainted(false);
        homeBtn.setContentAreaFilled(false);
        homeBtn.setDefaultCapable(false);
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeBtnMouseExited(evt);
            }
        });
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jPanel4.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(867, 0, 141, 53));

        backBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/Back.png"))); // NOI18N
        backBtn.setBorder(null);
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel4.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 1120, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    //show the details in the table that user click
    private void usersdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersdetailsMouseClicked
        int a = usersdetails.getSelectedRow();
        TableModel model = usersdetails.getModel();
        selectId = (int) model.getValueAt(a, 0);
        selectPos = model.getValueAt(a, 4).toString();
        selectStatus = model.getValueAt(a, 2).toString();

        if ("admin".equals(selectPos)) {
            Admin.setSelected(true);

        }
        if ("staff".equals(selectPos)) {
            Staff.setSelected(true);
        }

        if ("single".equals(selectStatus)) {
            Single.setSelected(true);
        }
        if ("married".equals(selectStatus)) {
            Married.setSelected(true);
        }

        ID.setText(model.getValueAt(a, 0).toString());
        username.setText(model.getValueAt(a, 5).toString());
        fullname.setText(model.getValueAt(a, 1).toString());
        salary.setText(model.getValueAt(a, 3).toString());
        password.setText(model.getValueAt(a, 6).toString());

    }//GEN-LAST:event_usersdetailsMouseClicked

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) usersdetails.getModel();
        model.setRowCount(0);
        showUsers();
    }//GEN-LAST:event_refreshBtnActionPerformed

    //update the details that showed in the text box
    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed

        String mstatus = null;
        String jobtitle = null;
        String name = fullname.getText();
        int Salary = Integer.parseInt(salary.getText());
        String Password = password.getText();
        String Username = username.getText();

        if (Single.isSelected()) {
            mstatus = "single";
        }
        if (Married.isSelected()) {
            mstatus = "married";
        }
        if (Admin.isSelected()) {
            jobtitle = "admin";
        }
        if (Staff.isSelected()) {
            jobtitle = "staff";
        }

        if ("admin".equals(selectPos)) {
            JOptionPane.showMessageDialog(null, "You cannot update Admin Information");
        } else {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you really want to update this user?", "Warning", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {
                Admin admin = new Admin();
                admin.update(mstatus, jobtitle, name, Salary, Password, Username);
                pos.clearSelection();
                status.clearSelection();
                ID.setText("");
                fullname.setText("");
                salary.setText("");
                username.setText("");
                password.setText("");
                DefaultTableModel model = (DefaultTableModel) usersdetails.getModel();
                model.setRowCount(0);
                showUsers();
            } else {
                JOptionPane.showMessageDialog(null, "User update is cancelled.");
            }
        }


    }//GEN-LAST:event_updateBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        if (back.equals("details")) {
            StaffDetails staff = new StaffDetails(userName, jobTitle);
            FadeUtilityClass fades = new FadeUtilityClass();
            fades.fade(staff, true);
            staff.setVisible(true);
            setVisible(false);
        } else {
            ManageStaff manage = new ManageStaff(userName, jobTitle);
            FadeUtilityClass fades = new FadeUtilityClass();
            fades.fade(manage, true);
            manage.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_backBtnActionPerformed

    private void refreshBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshBtnMouseEntered
        refreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/refresh1.png")));
    }//GEN-LAST:event_refreshBtnMouseEntered

    private void refreshBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshBtnMouseExited
        refreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/refresh.png")));
    }//GEN-LAST:event_refreshBtnMouseExited

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        Homepage home = new Homepage(userName, jobTitle);
        FadeUtilityClass fades = new FadeUtilityClass();
        fades.fade(home, true);
        home.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Do you really want to log out?", "Warning", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "User Log Out");
            User user = new User();
            FadeUtilityClass fades = new FadeUtilityClass();
            fades.fade(user, true);
            user.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void homeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseEntered
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/home1.png")));
    }//GEN-LAST:event_homeBtnMouseEntered

    private void homeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseExited
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/home.png")));
    }//GEN-LAST:event_homeBtnMouseExited

    private void logoutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseEntered
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/logout_1.png")));
    }//GEN-LAST:event_logoutBtnMouseEntered

    private void logoutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseExited
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/logout.png")));
    }//GEN-LAST:event_logoutBtnMouseExited

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed

        ID.setText("");
        fullname.setText("");
        salary.setText("");
        username.setText("");
        password.setText("");
        pos.clearSelection();
        status.clearSelection();;
    }//GEN-LAST:event_clearBtnActionPerformed

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/back1.png")));
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/Back.png")));
    }//GEN-LAST:event_backBtnMouseExited

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed

       if(Staff.isSelected()) 
        {
        if (viewBtn.isSelected()) {
            password.setEchoChar((char) 0);
           viewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/view.png")));
        } else {
            password.setEchoChar('*');
            viewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/unview.png")));
        }
        }
        else
        {
              JOptionPane.showMessageDialog(null, "You cannot view admin password");
        }
    }//GEN-LAST:event_viewBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateUser().setVisible(true);
            }
        });
    }

    //put the user list from the database in the usersList
    public ArrayList<Admin> usersList() {
        ArrayList<Admin> usersList = new ArrayList<>();
        try {
            Class.forName("com.mysql.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql://110.4.45.41:3306/myvoicem_sms", "myvoicem_admin", "Pintechpintech1");
            String sql = "Select * from login ";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            Admin users;
            while (rs.next()) {
                users = new Admin(rs.getInt("ID"), rs.getInt("salary"), rs.getString("name"), rs.getString("maritial_status"), rs.getString("username"), rs.getString("job_title"), rs.getString("password"));
                usersList.add(users);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return usersList;
    }

    //show the users in the table
    private void showUsers() {
        ArrayList<Admin> list = usersList();
        DefaultTableModel model = (DefaultTableModel) usersdetails.getModel();
        Object[] row = new Object[7];
        for (int i = 0; i < list.size(); i++) {

            row[0] = list.get(i).getId();
            row[1] = list.get(i).getName();
            row[2] = list.get(i).getMaritial_status();
            row[3] = list.get(i).getSalary();
            row[4] = list.get(i).getJob_title();
            row[5] = list.get(i).getUsername();
            if(list.get(i).getJob_title().equals("admin"))
            {
            row[6] = "****";
            }
            else
            {
            row[6] = list.get(i).getPassword(); 
            }
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Admin;
    private javax.swing.JTextField ID;
    private javax.swing.JRadioButton Married;
    private javax.swing.JRadioButton Single;
    private javax.swing.JRadioButton Staff;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JTextField fullname;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPasswordField password;
    private javax.swing.ButtonGroup pos;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTextField salary;
    private javax.swing.ButtonGroup status;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTextField username;
    private javax.swing.JTable usersdetails;
    private javax.swing.JToggleButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
