/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package staffmanagementsystem;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class User extends javax.swing.JFrame {

    public User() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.ButtonGroup();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        view = new javax.swing.JToggleButton();
        password = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();
        exitbutton = new javax.swing.JButton();
        staffPos = new javax.swing.JRadioButton();
        adminPos = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        loginbutton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        view.setBackground(new java.awt.Color(51, 0, 51));
        view.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/unview.png"))); // NOI18N
        view.setBorder(null);
        view.setBorderPainted(false);
        view.setContentAreaFilled(false);
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        jPanel1.add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 40, 38));

        password.setBackground(new java.awt.Color(51, 0, 51));
        password.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setBorder(null);
        password.setOpaque(false);
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
        });
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 320, 38));

        username.setBackground(new java.awt.Color(51, 0, 51));
        username.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setToolTipText("");
        username.setBorder(null);
        username.setOpaque(false);
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameMouseClicked(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 320, 40));

        exitbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exitbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/exit.png"))); // NOI18N
        exitbutton.setBorder(null);
        exitbutton.setBorderPainted(false);
        exitbutton.setContentAreaFilled(false);
        exitbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitbuttonMouseExited(evt);
            }
        });
        exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(exitbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 50, 50));

        staffPos.setBackground(new java.awt.Color(51, 0, 51));
        title.add(staffPos);
        staffPos.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        staffPos.setForeground(new java.awt.Color(255, 255, 255));
        staffPos.setText("Staff");
        jPanel1.add(staffPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, -1, -1));

        adminPos.setBackground(new java.awt.Color(51, 0, 51));
        title.add(adminPos);
        adminPos.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        adminPos.setForeground(new java.awt.Color(255, 255, 255));
        adminPos.setText("Admin");
        adminPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminPosActionPerformed(evt);
            }
        });
        jPanel1.add(adminPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 320, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 320, 20));

        loginbutton.setBackground(new java.awt.Color(255, 153, 255));
        loginbutton.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        loginbutton.setForeground(new java.awt.Color(255, 255, 255));
        loginbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/login.png"))); // NOI18N
        loginbutton.setBorder(null);
        loginbutton.setContentAreaFilled(false);
        loginbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginbuttonMouseExited(evt);
            }
        });
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(loginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, 120, 50));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Staff Management System");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 450, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 620, 620));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/staff1.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseClicked

    }//GEN-LAST:event_usernameMouseClicked

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked

    }//GEN-LAST:event_passwordMouseClicked

    //when user click the login button, it pass the value entered and compared to the data in database to check whether it is a valid account
    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed

        String jobTitle = "";
        if (password.getText().equals("") || username.getText().equals("") || !staffPos.isSelected() && !adminPos.isSelected()) {
            JOptionPane.showMessageDialog(null, "Please fill in all of the required information");
        } else {
            if (staffPos.isSelected()) {
                Staff staff = new Staff();
                jobTitle = "staff";
                if (staff.login(username.getText(), password.getText(), jobTitle)) {
                    JOptionPane.showMessageDialog(null, "Logged in Successfully");
                    Homepage home = new Homepage(username.getText(), jobTitle);
                    FadeUtilityClass fades = new FadeUtilityClass();
                    fades.fade(home, true);
                    home.setVisible(true);
                    setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Mismatched user id and password or id not exist");
                }
            }
            if (adminPos.isSelected()) {
                Admin admin = new Admin();
                jobTitle = "admin";
                if (admin.login(username.getText(), password.getText(), jobTitle)) {
                    JOptionPane.showMessageDialog(null, "Logged in Successfully");
                    Homepage home = new Homepage(username.getText(), jobTitle);
                    FadeUtilityClass fades = new FadeUtilityClass();
                    fades.fade(home, true);
                    home.setVisible(true);
                    setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Mismatched user id and password or id not exist");
                }

            }
        }
    }//GEN-LAST:event_loginbuttonActionPerformed

    //when user click the exit button, it shows a dialog for user to decide whether want to exit the program or not
    private void exitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttonActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Do you really want to exit?", "Warning", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Program Exit");
            System.exit(0);
        }
    }//GEN-LAST:event_exitbuttonActionPerformed

    private void adminPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminPosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminPosActionPerformed

    //user can view or unview the password
    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        if (view.isSelected()) {
            password.setEchoChar((char) 0);
           view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/view.png")));
        } else {
            password.setEchoChar('*');
            view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/unview.png")));
        }
    }//GEN-LAST:event_viewActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void loginbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbuttonMouseEntered
        loginbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/login1.png")));
    }//GEN-LAST:event_loginbuttonMouseEntered

    private void loginbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbuttonMouseExited
        loginbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/login.png")));
    }//GEN-LAST:event_loginbuttonMouseExited

    private void exitbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbuttonMouseEntered
        exitbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/exit_1.png")));
    }//GEN-LAST:event_exitbuttonMouseEntered

    private void exitbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbuttonMouseExited
        exitbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/Image/exit.png")));
    }//GEN-LAST:event_exitbuttonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adminPos;
    private javax.swing.JButton exitbutton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton loginbutton;
    private javax.swing.JPasswordField password;
    private javax.swing.JRadioButton staffPos;
    private javax.swing.ButtonGroup title;
    private javax.swing.JTextField username;
    private javax.swing.JToggleButton view;
    // End of variables declaration//GEN-END:variables
}
